"""Chapter 8: Password hashing with Werkzeug (8a)

Revision ID: 26fe181cbde0
Revises: be4ea6681356
Create Date: 2018-03-09 10:27:21.895791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26fe181cbde0'
down_revision = 'be4ea6681356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
