"""caching of avatar hashes

Revision ID: 688a4625fe2a
Revises: 739bcf74cfa3
Create Date: 2018-03-23 14:18:04.255586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688a4625fe2a'
down_revision = '739bcf74cfa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
